[package]
name = "rusty-trumpet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rusty-trumpet"
path = "src/main.rs"

[dependencies]
